'''
Be careful when modifying these values - if they aren't set correctly, 
the program won't run. As a precaution if you modify it, it's a good idea to 
save a copy first. serialplot just looks for a file in the same directory 
called 'defaults.py'
 
The format for graphXlineX properties is:
[datalabel,
datapos,
linecolor,
dashed,
multiplier,
offset]
'''

defaults = {'COMport': '',
 'baud': 115200,
 'databits': 8,
 'datadepth': 200,
 'datalength': 8,
 'filename': 'C:/Users/Victor/Desktop/GraphLog.csv',
 'g1ylims': [-3, 3],
 'g2ylims': [-3, 3],
 'g3ylims': [-400, 400],
 'graph1line1': ['Horizontal Position',
                 1,
                 '#FF0000',
                 '-',
                 '0.000635',
                 '-8.2931'],
 'graph1line2': ['Horizontal Setpoint',
                 2,
                 '#FF0000',
                 '--',
                 '0.000635',
                 '-8.2931'],
 'graph1line3': ['data3', '-', '#00FF00', '-', 1, 0],
 'graph2line1': ['Vertical Position',
                 5,
                 '#0000FF',
                 '-',
                 '-0.000635',
                 '7.223125'],
 'graph2line2': ['Vertical Setpoint',
                 6,
                 '#0000FF',
                 '--',
                 '-0.000635',
                 '7.223125'],
 'graph2line3': ['data3', '-', '#00FF00', '-', 1, 0],
 'graph3line1': ['Horizontal Control', 4, '#FF0000', '-', 1, 0],
 'graph3line2': ['Vertical Control', 8, '#0000FF', '-', 1, 0],
 'graph3line3': ['data3', '-', '#00FF00', '-', 1, 0],
 'log2file': 'off',
 'maxlength': 60,
 'numgraphs': 3,
 'parity': 'None',
 'refreshfreq': 30,
 'startmax': 'yes',
 'stopbits': 1,
 'stsbrwdth': 7}
